# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_ldm_ath.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13start_ldm_ath.proto\x12\rharmonyServer\"\xa5\x06\n\x0bStartLdmAth\x12\x12\n\nscenarioId\x18\x01 \x02(\t\x12\x31\n\x06inputs\x18\x02 \x02(\x0b\x32!.harmonyServer.StartLdmAth.Inputs\x12\x33\n\x07outputs\x18\x03 \x02(\x0b\x32\".harmonyServer.StartLdmAth.Outputs\x1a\xdd\x03\n\x06Inputs\x12\x14\n\x0cHRFloodzones\x18\x01 \x02(\t\x12\x16\n\x0e\x41thensBoundary\x18\x02 \x02(\t\x12\x14\n\x0cSurfaceWater\x18\x03 \x02(\t\x12\x10\n\x08Highways\x18\x04 \x02(\t\x12\x16\n\x0eProtectedAreas\x18\x05 \x02(\t\x12\x12\n\nNATURA2000\x18\x06 \x02(\t\x12\x17\n\x0fParksAndGardens\x18\x07 \x02(\t\x12\r\n\x05Slope\x18\x08 \x02(\t\x12\x19\n\x11PopulationDensity\x18\t \x02(\t\x12\x0e\n\x06GS2500\x18\n \x02(\t\x12\x1c\n\x14JobAccessibilitypr19\x18\x0b \x02(\t\x12\x1c\n\x14JobAccessibilitypr45\x18\x0c \x02(\t\x12\x1c\n\x14JobAccessibilitypu19\x18\r \x02(\t\x12\x1c\n\x14JobAccessibilitypu45\x18\x0e \x02(\t\x12 \n\x18HousingAccessibilitypr19\x18\x0f \x02(\t\x12 \n\x18HousingAccessibilitypr45\x18\x10 \x02(\t\x12 \n\x18HousingAccessibilitypu19\x18\x11 \x02(\t\x12 \n\x18HousingAccessibilitypu45\x18\x12 \x02(\t\x1a\xb9\x01\n\x07Outputs\x12\x15\n\rScenario1LD19\x18\x01 \x02(\t\x12\x15\n\rScenario1LD45\x18\x02 \x02(\t\x12\x13\n\x0bScenario1LS\x18\x03 \x02(\t\x12\x13\n\x0bSc1Diff1945\x18\x04 \x02(\t\x12\x15\n\rScenario2LD19\x18\x05 \x02(\t\x12\x15\n\rScenario2LD45\x18\x06 \x02(\t\x12\x13\n\x0bScenario2LS\x18\x07 \x02(\t\x12\x13\n\x0bSc2Diff1945\x18\x08 \x02(\t')



_STARTLDMATH = DESCRIPTOR.message_types_by_name['StartLdmAth']
_STARTLDMATH_INPUTS = _STARTLDMATH.nested_types_by_name['Inputs']
_STARTLDMATH_OUTPUTS = _STARTLDMATH.nested_types_by_name['Outputs']
StartLdmAth = _reflection.GeneratedProtocolMessageType('StartLdmAth', (_message.Message,), {

  'Inputs' : _reflection.GeneratedProtocolMessageType('Inputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTLDMATH_INPUTS,
    '__module__' : 'start_ldm_ath_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartLdmAth.Inputs)
    })
  ,

  'Outputs' : _reflection.GeneratedProtocolMessageType('Outputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTLDMATH_OUTPUTS,
    '__module__' : 'start_ldm_ath_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartLdmAth.Outputs)
    })
  ,
  'DESCRIPTOR' : _STARTLDMATH,
  '__module__' : 'start_ldm_ath_pb2'
  # @@protoc_insertion_point(class_scope:harmonyServer.StartLdmAth)
  })
_sym_db.RegisterMessage(StartLdmAth)
_sym_db.RegisterMessage(StartLdmAth.Inputs)
_sym_db.RegisterMessage(StartLdmAth.Outputs)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTLDMATH._serialized_start=39
  _STARTLDMATH._serialized_end=844
  _STARTLDMATH_INPUTS._serialized_start=179
  _STARTLDMATH_INPUTS._serialized_end=656
  _STARTLDMATH_OUTPUTS._serialized_start=659
  _STARTLDMATH_OUTPUTS._serialized_end=844
# @@protoc_insertion_point(module_scope)
