# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_tfs_ofs_data_transform.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='start_tfs_ofs_data_transform.proto',
  package='harmonyServer',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"start_tfs_ofs_data_transform.proto\x12\rharmonyServer\"\x8a\x06\n\x18StartTFSOFSDataTransform\x12\x12\n\nscenarioId\x18\x01 \x02(\t\x12>\n\x06inputs\x18\x02 \x02(\x0b\x32..harmonyServer.StartTFSOFSDataTransform.Inputs\x12@\n\x07outputs\x18\x03 \x02(\x0b\x32/.harmonyServer.StartTFSOFSDataTransform.Outputs\x1a\xaf\x04\n\x06Inputs\x12\x15\n\rModellingArea\x18\x01 \x02(\t\x12\x11\n\tNodesFile\x18\x02 \x02(\t\x12\x11\n\tLinksFile\x18\x03 \x02(\t\x12\x11\n\tZonesFile\x18\x04 \x02(\t\x12 \n\x18\x43onsolidationCentresFile\x18\x05 \x02(\t\x12\x15\n\rMicroHubsFile\x18\x06 \x02(\t\x12\x18\n\x10ParcelDemandFile\x18\x07 \x02(\t\x12\x1a\n\x12ShipmentDemandFile\x18\x08 \x02(\t\x12\x19\n\x11ShipmentToursFile\x18\t \x02(\t\x12\x17\n\x0fParcelToursFile\x18\n \x02(\t\x12\x1b\n\x13TravelTimesSkimFile\x18\x0b \x02(\t\x12\x19\n\x11\x44istancesSkimFile\x18\x0c \x02(\t\x12\x11\n\tReadNodes\x18\r \x02(\x08\x12\x11\n\tReadLinks\x18\x0e \x02(\x08\x12\x11\n\tReadZones\x18\x0f \x02(\x08\x12 \n\x18ReadConsolidationCentres\x18\x10 \x02(\x08\x12\x15\n\rReadMicrohubs\x18\x11 \x02(\x08\x12\x18\n\x10ReadParcelDemand\x18\x12 \x02(\x08\x12\x1b\n\x13ReadShipmentsDemand\x18\x13 \x02(\x08\x12\x1a\n\x12ReadShipmentsTours\x18\x14 \x02(\x08\x12\x17\n\x0fReadParcelTours\x18\x15 \x02(\x08\x12\x1c\n\x14ReadTravelTimesZones\x18\x16 \x02(\x08\x1a&\n\x07Outputs\x12\x1b\n\x13\x44\x61taTranformResults\x18\x01 \x02(\t'
)




_STARTTFSOFSDATATRANSFORM_INPUTS = _descriptor.Descriptor(
  name='Inputs',
  full_name='harmonyServer.StartTFSOFSDataTransform.Inputs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ModellingArea', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ModellingArea', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NodesFile', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.NodesFile', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LinksFile', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.LinksFile', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ZonesFile', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ZonesFile', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ConsolidationCentresFile', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ConsolidationCentresFile', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MicroHubsFile', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.MicroHubsFile', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ParcelDemandFile', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ParcelDemandFile', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ShipmentDemandFile', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ShipmentDemandFile', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ShipmentToursFile', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ShipmentToursFile', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ParcelToursFile', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ParcelToursFile', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TravelTimesSkimFile', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.TravelTimesSkimFile', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DistancesSkimFile', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.DistancesSkimFile', index=11,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReadNodes', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ReadNodes', index=12,
      number=13, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReadLinks', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ReadLinks', index=13,
      number=14, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReadZones', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ReadZones', index=14,
      number=15, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReadConsolidationCentres', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ReadConsolidationCentres', index=15,
      number=16, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReadMicrohubs', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ReadMicrohubs', index=16,
      number=17, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReadParcelDemand', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ReadParcelDemand', index=17,
      number=18, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReadShipmentsDemand', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ReadShipmentsDemand', index=18,
      number=19, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReadShipmentsTours', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ReadShipmentsTours', index=19,
      number=20, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReadParcelTours', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ReadParcelTours', index=20,
      number=21, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReadTravelTimesZones', full_name='harmonyServer.StartTFSOFSDataTransform.Inputs.ReadTravelTimesZones', index=21,
      number=22, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=792,
)

_STARTTFSOFSDATATRANSFORM_OUTPUTS = _descriptor.Descriptor(
  name='Outputs',
  full_name='harmonyServer.StartTFSOFSDataTransform.Outputs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='DataTranformResults', full_name='harmonyServer.StartTFSOFSDataTransform.Outputs.DataTranformResults', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=794,
  serialized_end=832,
)

_STARTTFSOFSDATATRANSFORM = _descriptor.Descriptor(
  name='StartTFSOFSDataTransform',
  full_name='harmonyServer.StartTFSOFSDataTransform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scenarioId', full_name='harmonyServer.StartTFSOFSDataTransform.scenarioId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='harmonyServer.StartTFSOFSDataTransform.inputs', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='harmonyServer.StartTFSOFSDataTransform.outputs', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STARTTFSOFSDATATRANSFORM_INPUTS, _STARTTFSOFSDATATRANSFORM_OUTPUTS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=832,
)

_STARTTFSOFSDATATRANSFORM_INPUTS.containing_type = _STARTTFSOFSDATATRANSFORM
_STARTTFSOFSDATATRANSFORM_OUTPUTS.containing_type = _STARTTFSOFSDATATRANSFORM
_STARTTFSOFSDATATRANSFORM.fields_by_name['inputs'].message_type = _STARTTFSOFSDATATRANSFORM_INPUTS
_STARTTFSOFSDATATRANSFORM.fields_by_name['outputs'].message_type = _STARTTFSOFSDATATRANSFORM_OUTPUTS
DESCRIPTOR.message_types_by_name['StartTFSOFSDataTransform'] = _STARTTFSOFSDATATRANSFORM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartTFSOFSDataTransform = _reflection.GeneratedProtocolMessageType('StartTFSOFSDataTransform', (_message.Message,), {

  'Inputs' : _reflection.GeneratedProtocolMessageType('Inputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTTFSOFSDATATRANSFORM_INPUTS,
    '__module__' : 'start_tfs_ofs_data_transform_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartTFSOFSDataTransform.Inputs)
    })
  ,

  'Outputs' : _reflection.GeneratedProtocolMessageType('Outputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTTFSOFSDATATRANSFORM_OUTPUTS,
    '__module__' : 'start_tfs_ofs_data_transform_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartTFSOFSDataTransform.Outputs)
    })
  ,
  'DESCRIPTOR' : _STARTTFSOFSDATATRANSFORM,
  '__module__' : 'start_tfs_ofs_data_transform_pb2'
  # @@protoc_insertion_point(class_scope:harmonyServer.StartTFSOFSDataTransform)
  })
_sym_db.RegisterMessage(StartTFSOFSDataTransform)
_sym_db.RegisterMessage(StartTFSOFSDataTransform.Inputs)
_sym_db.RegisterMessage(StartTFSOFSDataTransform.Outputs)


# @@protoc_insertion_point(module_scope)
