# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_abmd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10start_abmd.proto\x12\rharmonyServer\"\xc5\x01\n\tStartAbmd\x12\x12\n\nscenarioId\x18\x01 \x02(\t\x12/\n\x06inputs\x18\x02 \x02(\x0b\x32\x1f.harmonyServer.StartAbmd.Inputs\x12\x31\n\x07outputs\x18\x03 \x02(\x0b\x32 .harmonyServer.StartAbmd.Outputs\x1a\x1d\n\x06Inputs\x12\x13\n\x0bRWFORAPOLLO\x18\x01 \x02(\t\x1a!\n\x07Outputs\x12\x16\n\x0eMNLSPestimates\x18\x01 \x02(\t')



_STARTABMD = DESCRIPTOR.message_types_by_name['StartAbmd']
_STARTABMD_INPUTS = _STARTABMD.nested_types_by_name['Inputs']
_STARTABMD_OUTPUTS = _STARTABMD.nested_types_by_name['Outputs']
StartAbmd = _reflection.GeneratedProtocolMessageType('StartAbmd', (_message.Message,), {

  'Inputs' : _reflection.GeneratedProtocolMessageType('Inputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTABMD_INPUTS,
    '__module__' : 'start_abmd_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartAbmd.Inputs)
    })
  ,

  'Outputs' : _reflection.GeneratedProtocolMessageType('Outputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTABMD_OUTPUTS,
    '__module__' : 'start_abmd_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartAbmd.Outputs)
    })
  ,
  'DESCRIPTOR' : _STARTABMD,
  '__module__' : 'start_abmd_pb2'
  # @@protoc_insertion_point(class_scope:harmonyServer.StartAbmd)
  })
_sym_db.RegisterMessage(StartAbmd)
_sym_db.RegisterMessage(StartAbmd.Inputs)
_sym_db.RegisterMessage(StartAbmd.Outputs)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTABMD._serialized_start=36
  _STARTABMD._serialized_end=233
  _STARTABMD_INPUTS._serialized_start=169
  _STARTABMD_INPUTS._serialized_end=198
  _STARTABMD_OUTPUTS._serialized_start=200
  _STARTABMD_OUTPUTS._serialized_end=233
# @@protoc_insertion_point(module_scope)
