# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_tfs.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='start_tfs.proto',
  package='harmonyServer',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0fstart_tfs.proto\x12\rharmonyServer\"\xb6\x03\n\rStartTFSModel\x12\x15\n\rexperiment_id\x18\x01 \x02(\t\x12\r\n\x05LABEL\x18\x02 \x02(\t\x12\x12\n\nYEARFACTOR\x18\x03 \x02(\x05\x12\x17\n\x0fNUTSLEVEL_INPUT\x18\x04 \x02(\x05\x12\x17\n\x0fPARCELS_MAXLOAD\x18\x05 \x02(\x05\x12\x18\n\x10PARCELS_DROPTIME\x18\x06 \x02(\x05\x12\x16\n\x0ePARCELS_PER_HH\x18\x07 \x02(\x02\x12\x18\n\x10PARCELS_PER_EMPL\x18\x08 \x02(\x02\x12\x1b\n\x13PARCELS_SUCCESS_B2C\x18\t \x02(\x02\x12\x1b\n\x13PARCELS_SUCCESS_B2B\x18\n \x02(\x02\x12\x1d\n\x15PARCELS_GROWTHFREIGHT\x18\x0b \x02(\x02\x12\x17\n\x0f\x43RW_PARCELSHARE\x18\x0c \x02(\x02\x12\x14\n\x0cN_MULTIROUTE\x18\r \x02(\x05\x12\x15\n\rCROWDSHIPPING\x18\x0e \x02(\t\x12\x1f\n\x17IMPEDANCE_SPEED_FREIGHT\x18\x0f \x02(\t\x12\x1b\n\x13IMPEDANCE_SPEED_VAN\x18\x10 \x02(\t\x12\x10\n\x08\x41LL_DATA\x18\x11 \x02(\t'
)




_STARTTFSMODEL = _descriptor.Descriptor(
  name='StartTFSModel',
  full_name='harmonyServer.StartTFSModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='experiment_id', full_name='harmonyServer.StartTFSModel.experiment_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LABEL', full_name='harmonyServer.StartTFSModel.LABEL', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='YEARFACTOR', full_name='harmonyServer.StartTFSModel.YEARFACTOR', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NUTSLEVEL_INPUT', full_name='harmonyServer.StartTFSModel.NUTSLEVEL_INPUT', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PARCELS_MAXLOAD', full_name='harmonyServer.StartTFSModel.PARCELS_MAXLOAD', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PARCELS_DROPTIME', full_name='harmonyServer.StartTFSModel.PARCELS_DROPTIME', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PARCELS_PER_HH', full_name='harmonyServer.StartTFSModel.PARCELS_PER_HH', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PARCELS_PER_EMPL', full_name='harmonyServer.StartTFSModel.PARCELS_PER_EMPL', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PARCELS_SUCCESS_B2C', full_name='harmonyServer.StartTFSModel.PARCELS_SUCCESS_B2C', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PARCELS_SUCCESS_B2B', full_name='harmonyServer.StartTFSModel.PARCELS_SUCCESS_B2B', index=9,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PARCELS_GROWTHFREIGHT', full_name='harmonyServer.StartTFSModel.PARCELS_GROWTHFREIGHT', index=10,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CRW_PARCELSHARE', full_name='harmonyServer.StartTFSModel.CRW_PARCELSHARE', index=11,
      number=12, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='N_MULTIROUTE', full_name='harmonyServer.StartTFSModel.N_MULTIROUTE', index=12,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CROWDSHIPPING', full_name='harmonyServer.StartTFSModel.CROWDSHIPPING', index=13,
      number=14, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IMPEDANCE_SPEED_FREIGHT', full_name='harmonyServer.StartTFSModel.IMPEDANCE_SPEED_FREIGHT', index=14,
      number=15, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IMPEDANCE_SPEED_VAN', full_name='harmonyServer.StartTFSModel.IMPEDANCE_SPEED_VAN', index=15,
      number=16, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ALL_DATA', full_name='harmonyServer.StartTFSModel.ALL_DATA', index=16,
      number=17, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=473,
)

DESCRIPTOR.message_types_by_name['StartTFSModel'] = _STARTTFSMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartTFSModel = _reflection.GeneratedProtocolMessageType('StartTFSModel', (_message.Message,), {
  'DESCRIPTOR' : _STARTTFSMODEL,
  '__module__' : 'start_tfs_pb2'
  # @@protoc_insertion_point(class_scope:harmonyServer.StartTFSModel)
  })
_sym_db.RegisterMessage(StartTFSModel)


# @@protoc_insertion_point(module_scope)
