# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_demo2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='start_demo2.proto',
  package='harmonyServer',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x11start_demo2.proto\x12\rharmonyServer\"\xa4\x02\n\x13StartDemo2Component\x12\x12\n\nscenarioId\x18\x01 \x02(\t\x12\x39\n\x06inputs\x18\x02 \x02(\x0b\x32).harmonyServer.StartDemo2Component.Inputs\x12;\n\x07outputs\x18\x03 \x02(\x0b\x32*.harmonyServer.StartDemo2Component.Outputs\x1a_\n\x06Inputs\x12\x14\n\x0cstring_input\x18\x01 \x02(\t\x12\x15\n\rnumeric_input\x18\x02 \x02(\x05\x12\x13\n\x0b\x64\x65mo2_file1\x18\x03 \x02(\t\x12\x13\n\x0b\x64\x65mo2_file2\x18\x04 \x02(\t\x1a \n\x07Outputs\x12\x15\n\rdemo2_output1\x18\x01 \x02(\t'
)




_STARTDEMO2COMPONENT_INPUTS = _descriptor.Descriptor(
  name='Inputs',
  full_name='harmonyServer.StartDemo2Component.Inputs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_input', full_name='harmonyServer.StartDemo2Component.Inputs.string_input', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numeric_input', full_name='harmonyServer.StartDemo2Component.Inputs.numeric_input', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='demo2_file1', full_name='harmonyServer.StartDemo2Component.Inputs.demo2_file1', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='demo2_file2', full_name='harmonyServer.StartDemo2Component.Inputs.demo2_file2', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=295,
)

_STARTDEMO2COMPONENT_OUTPUTS = _descriptor.Descriptor(
  name='Outputs',
  full_name='harmonyServer.StartDemo2Component.Outputs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='demo2_output1', full_name='harmonyServer.StartDemo2Component.Outputs.demo2_output1', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=329,
)

_STARTDEMO2COMPONENT = _descriptor.Descriptor(
  name='StartDemo2Component',
  full_name='harmonyServer.StartDemo2Component',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scenarioId', full_name='harmonyServer.StartDemo2Component.scenarioId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='harmonyServer.StartDemo2Component.inputs', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='harmonyServer.StartDemo2Component.outputs', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STARTDEMO2COMPONENT_INPUTS, _STARTDEMO2COMPONENT_OUTPUTS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=329,
)

_STARTDEMO2COMPONENT_INPUTS.containing_type = _STARTDEMO2COMPONENT
_STARTDEMO2COMPONENT_OUTPUTS.containing_type = _STARTDEMO2COMPONENT
_STARTDEMO2COMPONENT.fields_by_name['inputs'].message_type = _STARTDEMO2COMPONENT_INPUTS
_STARTDEMO2COMPONENT.fields_by_name['outputs'].message_type = _STARTDEMO2COMPONENT_OUTPUTS
DESCRIPTOR.message_types_by_name['StartDemo2Component'] = _STARTDEMO2COMPONENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartDemo2Component = _reflection.GeneratedProtocolMessageType('StartDemo2Component', (_message.Message,), {

  'Inputs' : _reflection.GeneratedProtocolMessageType('Inputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTDEMO2COMPONENT_INPUTS,
    '__module__' : 'start_demo2_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartDemo2Component.Inputs)
    })
  ,

  'Outputs' : _reflection.GeneratedProtocolMessageType('Outputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTDEMO2COMPONENT_OUTPUTS,
    '__module__' : 'start_demo2_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartDemo2Component.Outputs)
    })
  ,
  'DESCRIPTOR' : _STARTDEMO2COMPONENT,
  '__module__' : 'start_demo2_pb2'
  # @@protoc_insertion_point(class_scope:harmonyServer.StartDemo2Component)
  })
_sym_db.RegisterMessage(StartDemo2Component)
_sym_db.RegisterMessage(StartDemo2Component.Inputs)
_sym_db.RegisterMessage(StartDemo2Component.Outputs)


# @@protoc_insertion_point(module_scope)
