# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_sfs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstart_sfs.proto\x12\rharmonyServer\"\xf3\x03\n\x08StartSFS\x12\x12\n\nscenarioId\x18\x01 \x02(\t\x12.\n\x06inputs\x18\x02 \x02(\x0b\x32\x1e.harmonyServer.StartSFS.Inputs\x12\x30\n\x07outputs\x18\x03 \x02(\x0b\x32\x1f.harmonyServer.StartSFS.Outputs\x1a\xb8\x02\n\x06Inputs\x12\r\n\x05label\x18\x01 \x02(\t\x12\x0f\n\x07modules\x18\x02 \x02(\t\x12\x12\n\ndimensions\x18\x03 \x02(\t\x12\r\n\x05zones\x18\x04 \x02(\t\x12\x0c\n\x04segs\x18\x05 \x02(\t\x12\x17\n\x0f\x63ommodityMatrix\x18\x06 \x02(\t\x12\x1b\n\x13\x64istributionCenters\x18\x07 \x02(\t\x12\x12\n\nDCoppNUTS3\x18\x08 \x02(\t\x12\x15\n\rparamsProdSIF\x18\t \x02(\t\x12\x15\n\rparamsAttrSIF\x18\n \x02(\t\x12\x13\n\x0bMRDHtoNUTS3\x18\x0b \x02(\t\x12\x13\n\x0bNUTS3toMRDH\x18\x0c \x02(\t\x12\x11\n\tSBItoSegs\x18\r \x02(\t\x12\x10\n\x08\x66irmSize\x18\x0e \x02(\t\x12\x16\n\x0enutsLevelInput\x18\x0f \x02(\x05\x1a\x36\n\x07Outputs\x12\r\n\x05\x66irms\x18\x01 \x02(\t\x12\x1c\n\x14\x63ommodityMatrixNUTS3\x18\x02 \x02(\t')



_STARTSFS = DESCRIPTOR.message_types_by_name['StartSFS']
_STARTSFS_INPUTS = _STARTSFS.nested_types_by_name['Inputs']
_STARTSFS_OUTPUTS = _STARTSFS.nested_types_by_name['Outputs']
StartSFS = _reflection.GeneratedProtocolMessageType('StartSFS', (_message.Message,), {

  'Inputs' : _reflection.GeneratedProtocolMessageType('Inputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTSFS_INPUTS,
    '__module__' : 'start_sfs_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartSFS.Inputs)
    })
  ,

  'Outputs' : _reflection.GeneratedProtocolMessageType('Outputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTSFS_OUTPUTS,
    '__module__' : 'start_sfs_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartSFS.Outputs)
    })
  ,
  'DESCRIPTOR' : _STARTSFS,
  '__module__' : 'start_sfs_pb2'
  # @@protoc_insertion_point(class_scope:harmonyServer.StartSFS)
  })
_sym_db.RegisterMessage(StartSFS)
_sym_db.RegisterMessage(StartSFS.Inputs)
_sym_db.RegisterMessage(StartSFS.Outputs)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTSFS._serialized_start=35
  _STARTSFS._serialized_end=534
  _STARTSFS_INPUTS._serialized_start=166
  _STARTSFS_INPUTS._serialized_end=478
  _STARTSFS_OUTPUTS._serialized_start=480
  _STARTSFS_OUTPUTS._serialized_end=534
# @@protoc_insertion_point(module_scope)
