# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_demo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='start_demo.proto',
  package='harmonyServer',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x10start_demo.proto\x12\rharmonyServer\"\x9b\x01\n\x12StartDemoComponent\x12\x12\n\nscenarioID\x18\x01 \x02(\t\x12\r\n\x05title\x18\x02 \x02(\t\x12\x12\n\nmultiplier\x18\x03 \x02(\x05\x12\r\n\x05\x63ount\x18\x04 \x02(\t\x12\x11\n\tfirstFile\x18\x05 \x02(\t\x12\x12\n\nsecondFile\x18\x06 \x02(\t\x12\x18\n\x10outputFolderPath\x18\x07 \x02(\t'
)




_STARTDEMOCOMPONENT = _descriptor.Descriptor(
  name='StartDemoComponent',
  full_name='harmonyServer.StartDemoComponent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scenarioID', full_name='harmonyServer.StartDemoComponent.scenarioID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='harmonyServer.StartDemoComponent.title', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='multiplier', full_name='harmonyServer.StartDemoComponent.multiplier', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='harmonyServer.StartDemoComponent.count', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='firstFile', full_name='harmonyServer.StartDemoComponent.firstFile', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secondFile', full_name='harmonyServer.StartDemoComponent.secondFile', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputFolderPath', full_name='harmonyServer.StartDemoComponent.outputFolderPath', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['StartDemoComponent'] = _STARTDEMOCOMPONENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartDemoComponent = _reflection.GeneratedProtocolMessageType('StartDemoComponent', (_message.Message,), {
  'DESCRIPTOR' : _STARTDEMOCOMPONENT,
  '__module__' : 'start_demo_pb2'
  # @@protoc_insertion_point(class_scope:harmonyServer.StartDemoComponent)
  })
_sym_db.RegisterMessage(StartDemoComponent)


# @@protoc_insertion_point(module_scope)
