# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_rem.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstart_rem.proto\x12\rharmonyServer\"\x8d\x05\n\x08StartREM\x12\x12\n\nscenarioId\x18\x01 \x02(\t\x12.\n\x06inputs\x18\x02 \x02(\x0b\x32\x1e.harmonyServer.StartREM.Inputs\x12\x30\n\x07outputs\x18\x03 \x02(\x0b\x32\x1f.harmonyServer.StartREM.Outputs\x1a\xf5\x01\n\x06Inputs\x12\x10\n\x08\x42\x61seJobs\x18\x01 \x02(\t\x12\x11\n\tbetaCoeff\x18\x02 \x02(\t\x12\x0f\n\x07MacroEc\x18\x03 \x02(\t\x12\x0f\n\x07MicroEc\x18\x04 \x02(\t\x12\x14\n\x0cTotPopByYear\x18\x05 \x02(\t\x12\x11\n\tTechCoeff\x18\x06 \x02(\t\x12\x12\n\nTrendsCnst\x18\x07 \x02(\t\x12\x11\n\tTrendsPar\x18\x08 \x02(\t\x12\x18\n\x10zoneDistribution\x18\t \x02(\t\x12\x12\n\nBaseIncome\x18\n \x02(\t\x12\x0f\n\x07yearOut\x18\x0b \x02(\t\x12\x15\n\rZoneShapefile\x18\x0c \x02(\t\x1a\x92\x02\n\x07Outputs\x12\x12\n\nYearlyJobs\x18\x01 \x02(\t\x12\x16\n\x0eYearlyJobsXlsx\x18\x02 \x02(\t\x12\x16\n\x0eYearlyJobsZone\x18\x03 \x02(\t\x12 \n\x18YearlyJobsZoneAggregated\x18\x04 \x02(\t\x12\x0e\n\x06Income\x18\x05 \x02(\t\x12\x1c\n\x14YearlyJobsZoneAggrY0\x18\x06 \x02(\t\x12\x1c\n\x14YearlyJobsZoneAggrY1\x18\x07 \x02(\t\x12\x1c\n\x14YearlyJobsZoneAggrY2\x18\x08 \x02(\t\x12\x11\n\tMapJobsY1\x18\t \x02(\t\x12\x11\n\tMapJobsY2\x18\n \x02(\t\x12\x11\n\tMapJobsY3\x18\x0b \x02(\t')



_STARTREM = DESCRIPTOR.message_types_by_name['StartREM']
_STARTREM_INPUTS = _STARTREM.nested_types_by_name['Inputs']
_STARTREM_OUTPUTS = _STARTREM.nested_types_by_name['Outputs']
StartREM = _reflection.GeneratedProtocolMessageType('StartREM', (_message.Message,), {

  'Inputs' : _reflection.GeneratedProtocolMessageType('Inputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTREM_INPUTS,
    '__module__' : 'start_rem_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartREM.Inputs)
    })
  ,

  'Outputs' : _reflection.GeneratedProtocolMessageType('Outputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTREM_OUTPUTS,
    '__module__' : 'start_rem_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartREM.Outputs)
    })
  ,
  'DESCRIPTOR' : _STARTREM,
  '__module__' : 'start_rem_pb2'
  # @@protoc_insertion_point(class_scope:harmonyServer.StartREM)
  })
_sym_db.RegisterMessage(StartREM)
_sym_db.RegisterMessage(StartREM.Inputs)
_sym_db.RegisterMessage(StartREM.Outputs)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTREM._serialized_start=35
  _STARTREM._serialized_end=688
  _STARTREM_INPUTS._serialized_start=166
  _STARTREM_INPUTS._serialized_end=411
  _STARTREM_OUTPUTS._serialized_start=414
  _STARTREM_OUTPUTS._serialized_end=688
# @@protoc_insertion_point(module_scope)
