# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: output_produced.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='output_produced.proto',
  package='harmonyServer',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x15output_produced.proto\x12\rharmonyServer\"Q\n\x1eUpdateServerWithOutputMetaData\x12\x13\n\x0bSCENARIO_ID\x18\x01 \x02(\t\x12\x0b\n\x03KEY\x18\x02 \x02(\t\x12\r\n\x05VALUE\x18\x03 \x02(\t'
)




_UPDATESERVERWITHOUTPUTMETADATA = _descriptor.Descriptor(
  name='UpdateServerWithOutputMetaData',
  full_name='harmonyServer.UpdateServerWithOutputMetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SCENARIO_ID', full_name='harmonyServer.UpdateServerWithOutputMetaData.SCENARIO_ID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='KEY', full_name='harmonyServer.UpdateServerWithOutputMetaData.KEY', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VALUE', full_name='harmonyServer.UpdateServerWithOutputMetaData.VALUE', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['UpdateServerWithOutputMetaData'] = _UPDATESERVERWITHOUTPUTMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateServerWithOutputMetaData = _reflection.GeneratedProtocolMessageType('UpdateServerWithOutputMetaData', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESERVERWITHOUTPUTMETADATA,
  '__module__' : 'output_produced_pb2'
  # @@protoc_insertion_point(class_scope:harmonyServer.UpdateServerWithOutputMetaData)
  })
_sym_db.RegisterMessage(UpdateServerWithOutputMetaData)


# @@protoc_insertion_point(module_scope)
