# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_tfs.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='start_tfs.proto',
  package='harmonyServer',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0fstart_tfs.proto\x12\rharmonyServer\"&\n\rStartTFSModel\x12\x15\n\rexperiment_id\x18\x01 \x02(\t'
)




_STARTTFSMODEL = _descriptor.Descriptor(
  name='StartTFSModel',
  full_name='harmonyServer.StartTFSModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='experiment_id', full_name='harmonyServer.StartTFSModel.experiment_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['StartTFSModel'] = _STARTTFSMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartTFSModel = _reflection.GeneratedProtocolMessageType('StartTFSModel', (_message.Message,), {
  'DESCRIPTOR' : _STARTTFSMODEL,
  '__module__' : 'start_tfs_pb2'
  # @@protoc_insertion_point(class_scope:harmonyServer.StartTFSModel)
  })
_sym_db.RegisterMessage(StartTFSModel)


# @@protoc_insertion_point(module_scope)
